dataset_test: visa
dataset_train: mvtec

test_data_path: ./data/visa
train_data_path: ./data/mvtec

model: ViT-L-14-336
pretrained: openai
features_list: [6, 12, 18, 24]
few_shot_features: [6, 12, 18, 24]
image_size: 518

k_shot: 4
seed: 10
epoch: 3
save_freq: 3
device: cuda:0

mask_topk: 100
mask_th: 0.5
mask_weight: [1.2, 0.8]
mask_layers: [12, 18, 24]

lambd: 0.72
region_alpha: 0.2


clip_config_path: ./open_clip/model_configs/ViT-L-14-336.json
save_path: ./result/visa
checkpoint_path: ./result/visa/epoch_3.pth